services:
  apigateway:
    extends:
      file: ./infrastructure/krakend/docker-compose.yml
      service: krakend
    depends_on:
      - redis
  redis:
    extends:
      file: ./infrastructure/redis/docker-compose.yml
      service: redis
  postgres:
    extends:
      file: ./infrastructure/postgres/docker-compose.yml
      service: postgres
  zitadel:
    extends:
      file: ./infrastructure/zitadel/docker-compose.yml
      service: zitadel

networks:
  sd-001-link-shortener:
