.PHONY: docker_local dev

# ==============================================================================
# Docker compose commands

docker_local:
	echo "Starting local environment"
	docker compose -f docker-compose.yml up -d

# ==============================================================================
# Application commands

dev:
	air
