services:
  postgres:
    restart: 'always'
    image: postgres:17-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pocketlink
    networks:
      - sd-001-link-shortener
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'zitadel', '-U', 'postgres']
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
